### ISSUE TITLE
Why must the window shift divide window length?

### ISSUE THREAD

**Issue by TheButlah** [Jonathan-LeRoux/lws#10]
Hi,

I'm looking at using LWS instead of the griffin lim algorithm from [librosa](https://librosa.github.io/librosa/generated/librosa.core.griffinlim.html?highlight=griffinlim#librosa.core.griffinlim). I am performing phase reconstruction on magnitude spectrograms for generative speech synthesis.

My (already trained) model outputs spectrograms with a hop size of 256, and the data it is training on is generated by librosa's [stft](https://librosa.github.io/librosa/generated/librosa.core.stft.html) function, where it is hann windowed to a length of 1100 and then padded by zeros to a length of 2048 (presumably for efficiency reasons).

What I would like to know is if it is possible to use LWS under these settings. The library complains that the window length isn't divisible by the hop size. If I use the padded length of 2048 instead of the windowed length of 1100, will that work? 

Disclaimer: my background is not in signal processing (I'm an ML guy) so I'm out of my depth here, and might be misunderstanding something.

**Comment by Jonathan-LeRoux** [comment]
I was going to say no, but after thinking about it I believe it may actually work, even without zero-padding. 
I'm in the process of removing the error raising, and making the stft/istft code more robust.

**Comment by Jonathan-LeRoux** [comment]
I just pushed an update that should allow using window shifts that do not divide window length.
As I mentioned in https://github.com/Jonathan-LeRoux/lws/issues/11, you need to be careful when using lws on librosa spectrograms as some conventions may differ. I believe zero-padding for the FFT is the same (window equally padded on left and right), so that's okay. But librosa uses different amounts of zero-padding at the signal boundaries, resulting in a different number of frames, and weird boundary effects are likely to occur. If you add some silence around your signals, it should be fine.
