### ISSUE TITLE
Is it possible to use LWS on an already existing spectrogram?

### ISSUE THREAD

**Issue by TheButlah** [Jonathan-LeRoux/lws#11]
I'm trying to use lws on a spectrogram created using a different library for the STFT implementation. It outputs the spectrogram as a numpy array. I've attempted to pass it into `run_lws`, but it gives `ValueError: Buffer dtype mismatch, expected 'double_t' but got 'float'`

**Comment by Jonathan-LeRoux** [comment]
Sorry for the delay. Yes, it is possible, but currently the code does not convert to double, so you need to do it yourself, e.g.:
`X1 = lws_processor.run_lws(X0.astype(np.double))`
That being said, I don't understand why the code does not choke when called on a `'complex64'` array, only `'float32'`, when in both cases the code looks at the `.real` and `.imag` of the array, which are `'float32'`. The default type for complex arrays in lws is `'complex128'`.
I need to modify the code to convert by default to avoid such issues, thanks for pointing it out.

**Comment by Jonathan-LeRoux** [comment]
I take it back, the code _does_ choke on `'complex64'` arrays, I was confused. I modified the code to automatically convert to `'complex128'`. I'll upload the updated version in the next few days as I'm working on making the code work when the window shift does not divide the window length.

**Comment by Jonathan-LeRoux** [comment]
I pushed the new version. 
Note however that it is likely that the phase reconstruction code will not work out of the box with spectrograms obtained by other toolkits:
- you need to make sure to pass the exact analysis window used to create the original spectrogram to lws
- it is likely that librosa and other toolkits use different conventions when padding the signal at the boundaries for perfect reconstruction
- if using zero-padding for the FFT, be aware that lws uses symmetric zero-padding, i.e., the window is padded on the left and right equally, instead of putting all the zero-padding at the end.
